-- Выполнить один раз в Supabase SQL Editor. Не удаляет старые таблицы.
create extension if not exists pgcrypto;
create table if not exists public.studios (id uuid primary key default gen_random_uuid(), name text not null default 'Продвижение', owner_id uuid not null unique references auth.users(id), created_at timestamptz default now());
create table if not exists public.studio_members (studio_id uuid not null references public.studios(id), user_id uuid not null references auth.users(id), role text not null check(role in ('owner','employee','client')), approved boolean not null default false, trainer_id uuid references auth.users(id), share_percent numeric(5,2) not null default 50 check(share_percent between 0 and 100), primary key(studio_id,user_id));
create table if not exists public.studio_prices (studio_id uuid not null references public.studios(id), client_id uuid not null references auth.users(id), kind text not null check(kind in ('personal','mat_split','reformer_split','group')), amount numeric(12,2) not null check(amount>=0), primary key(studio_id,client_id,kind));
create table if not exists public.studio_ledger (id uuid primary key default gen_random_uuid(), studio_id uuid not null references public.studios(id), client_id uuid references auth.users(id), trainer_id uuid references auth.users(id), kind text not null check(kind in ('deposit','session','expense','refund')), amount numeric(12,2) not null check(amount>0), method text not null check(method in ('cash','card','transfer','other','deposit')), event_date date not null default current_date, note text not null default '', created_by uuid not null default auth.uid(), created_at timestamptz default now());
create or replace function public.is_studio_owner(s uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.studios where id=s and owner_id=auth.uid())$$;
create or replace function public.my_studio_role(s uuid) returns text language sql stable security definer set search_path=public as $$select role from public.studio_members where studio_id=s and user_id=auth.uid() and approved=true limit 1$$;
revoke all on function public.is_studio_owner(uuid) from public; revoke all on function public.my_studio_role(uuid) from public;
grant execute on function public.is_studio_owner(uuid),public.my_studio_role(uuid) to authenticated;
alter table public.studios enable row level security; alter table public.studio_members enable row level security; alter table public.studio_prices enable row level security; alter table public.studio_ledger enable row level security;
drop policy if exists studio_view on public.studios; create policy studio_view on public.studios for select to authenticated using (owner_id=auth.uid() or exists(select 1 from public.studio_members m where m.studio_id=id and m.user_id=auth.uid()));
drop policy if exists studio_create on public.studios; create policy studio_create on public.studios for insert to authenticated with check(owner_id=auth.uid());
drop policy if exists member_view on public.studio_members; create policy member_view on public.studio_members for select to authenticated using(public.is_studio_owner(studio_id) or user_id=auth.uid() or (public.my_studio_role(studio_id)='employee' and trainer_id=auth.uid() and approved));
drop policy if exists member_insert on public.studio_members; create policy member_insert on public.studio_members for insert to authenticated with check(public.is_studio_owner(studio_id) or (user_id=auth.uid() and role='client' and approved=false and trainer_id is null));
drop policy if exists member_update on public.studio_members; create policy member_update on public.studio_members for update to authenticated using(public.is_studio_owner(studio_id)) with check(public.is_studio_owner(studio_id));
drop policy if exists price_view on public.studio_prices; create policy price_view on public.studio_prices for select to authenticated using(public.is_studio_owner(studio_id) or (client_id=auth.uid() and public.my_studio_role(studio_id)='client') or exists(select 1 from public.studio_members m where m.studio_id=studio_prices.studio_id and m.user_id=studio_prices.client_id and m.trainer_id=auth.uid() and m.approved));
drop policy if exists price_write on public.studio_prices; create policy price_write on public.studio_prices for all to authenticated using(public.is_studio_owner(studio_id)) with check(public.is_studio_owner(studio_id));
drop policy if exists ledger_view on public.studio_ledger; create policy ledger_view on public.studio_ledger for select to authenticated using(public.is_studio_owner(studio_id) or (public.my_studio_role(studio_id)='employee' and trainer_id=auth.uid()) or (public.my_studio_role(studio_id)='client' and client_id=auth.uid() and kind in ('deposit','session','refund')));
drop policy if exists ledger_write on public.studio_ledger; create policy ledger_write on public.studio_ledger for insert to authenticated with check(public.is_studio_owner(studio_id) and created_by=auth.uid());
-- Клиент не может увидеть расходы, зарплаты или платежи других клиентов.
grant usage on schema public to authenticated; grant select,insert,update on public.studios,public.studio_members,public.studio_prices to authenticated; grant select,insert on public.studio_ledger to authenticated;
